global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: redpanda
    static_configs:
      - targets:
          - "172.24.1.1:19644"
          - "172.24.1.1:29644"
          - "172.24.1.1:39644"
